### ISSUE TITLE
Buttons for switching are misplaced

### ISSUE THREAD

**Issue by remiverdel** [KayelGee/control-concealer#14]
Hi,

On my screen with no other module active, the D, P and Edit buttons are completely misplaced preventing access.

I'm using the latest version of the module on V9

Here is a screen shot

<img width="329" alt="Capture d’écran 2022-03-09 à 17 05 01" src="https://user-images.githubusercontent.com/22896375/157480900-55c1e3da-5534-4579-b3f0-a42a3ad6a988.png">

**Comment by KayelGee** [comment]
Do you have any other modules active?

**Comment by remiverdel** [comment]
Hi,

No other module active on my end 


Rémi Verdel

**Comment by KayelGee** [comment]
Which browser is this?

**Comment by remiverdel** [comment]
I’m using Google Chrome

**Comment by KayelGee** [comment]
Are you on a high dpi screen by any chance?

**Comment by remiverdel** [comment]
Yes I’m on a 4K screen

**Comment by KayelGee** [comment]
Can you go into the devloper tools and select the `<li class="control-concealer-top">` element so the style is shown on the right like on the following screenshot and make a screenshot how it looks on your end?
![image](https://user-images.githubusercontent.com/20637397/157708483-96bb88f3-ee40-4679-bb23-8a9b793832f3.png)

**Comment by remiverdel** [comment]
Here it is. I reactivated all my modules for the screenshot as the result is the same with or without

**Comment by KayelGee** [comment]
I don't see anything. You probably need to attach the image directly in github

**Comment by remiverdel** [comment]
My bad, here it is.
<img width="2560" alt="46855D3F-082A-4A19-88FC-00CEE1D01CF9" src="https://user-images.githubusercontent.com/22896375/158011190-db12b825-c20b-4ce0-959b-b8189e446211.png">

**Comment by KayelGee** [comment]
ok so your style.css is missing the whole "#controls ol.control-tools > li" part. Either your browser cached the `style.css` from a previous version of foundry or you manually edited(or it didn't update correctly) the `style.css` in `FoundryVTT\resources\app\public\css`.

I'd suggest you clear the cache or check if your `style.css` is correct in your install.  Line 2470 should look like this: 
```css
#controls ol.control-tools > li {
  flex: none;
  width: 36px;
  height: 36px;
  margin: 0 0 10px 0;
  box-sizing: content-box;
  font-size: 24px;
  line-height: 36px;
  background: rgba(0, 0, 0, 0.5);
  box-shadow: 0 0 10px var(--color-shadow-dark);
  color: var(--color-text-light-heading);
  text-align: center;
  border: 1px solid var(--color-border-dark);
  border-radius: 5px;
  cursor: pointer;
  pointer-events: all;
  display: inline-block;
  /* Toggled Buttons */
}
```
